# Generated by Django 5.0.6 on 2024-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        help_text="name of user who is posting the question",
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="content of the question being asked from streamer"
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
                (
                    "host",
                    models.CharField(
                        help_text="user ip address, who posted this question as identity",
                        max_length=31,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
            },
        ),
    ]
